### ISSUE TITLE
No UI on macOS Mojave

### ISSUE THREAD

**Issue by Deltafire** [emoon/rocket#148] opened 2019-06-22 08:46 UTC
Window opens but it doesn't draw any UI elements.  It appears to connect to the client and I can start/stop playback.  I can also load an MP3 from the file menu, but hitting space doesn't produce any audio (not sure if that's expected behaviour).

**Comment by emoon** [comment] 2019-06-22 08:58
That sounds odd as I can run it fine on macOS Mojave here.

Can you post a screenshot of exactly how it looks like and also a bit of the specs of your machine. Loading MP3 is not used for musicplay back in RocketEditor but only for visualizing FFT. The demo/intro etc that RocketEditor connects to is always responsible for playing the actual audio

**Comment by Deltafire** [comment] 2019-06-22 14:31
<img width="1440" alt="Screenshot 2019-06-22 at 15 29 14" src="https://user-images.githubusercontent.com/555390/59965176-97c11f00-9502-11e9-85ad-b67c14274f63.png">

It's a 2018 Macbook Pro with Radeon 560X graphics.

**Comment by emoon** [comment] 2019-06-22 14:34
Really weird.. if you try the prebuilt version https://www.dropbox.com/s/toaiyfgzue9fm2v/RocketEditor1.2beta.zip?dl=0 do you get the same problem then as well?

**Comment by Deltafire** [comment] 2019-06-22 14:41
That seems to work fine, very strange!

Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0

**Comment by emoon** [comment] 2019-06-22 14:50
Maybe it's caused by changes that has been integrated but not correctly tested/verified on macOS. I haven't been changing the code for a while but I have accepted some PR so maybe something broke during that :/

**Comment by Deltafire** [comment] 2019-06-22 15:41
I've tried a version from a couple of years ago, still getting the same problem.

Will have another look later.

**Comment by einarf** [comment] 2019-06-22 17:49
`1.0` and `1.2 beta 1` have worked fine for me on a 2013 Macbook Pro with a 650M.

**Comment by Deltafire** [comment] 2019-06-26 17:30
I've tried a few things to get this to work, but with no luck.

To summarise:  The prebuilt version linked above works as expected, but any that I build myself show no GUI.

I have tried building several versions right back to v1.0, all with the same result.  I have also tried comparing the Cocoa setup code with that of MilkyTracker (this also uses OpenGL for it's GUI and works fine), but I've failed to discovered anything different that would cause MT to work, but Rocket not to.

Giving up for now!

**Comment by emoon** [comment] 2019-06-26 17:33
🤔 not sure what the issue can be

**Comment by emoon** [comment] 2019-07-04 07:42
Sorry I didn't get around to do it last weekend. I will try this one!

**Comment by emoon** [comment] 2019-07-05 16:05
Ok, I know what the problem is and it's an annoying one. With macOS Mojave or to be more correct the latest(ish) version of MacOS SDK Apple re-did how windows re setup and created. It broke a bunch of my other applications (such as https://github.com/emoon/rust_minifb) the way I solved it there was to rewrite the code to use Metal API instead for all the rendering.

Now this is totally doable here as well but a bunch of work. A workaround to get this working is to build against an older version of the SDK and everything will work again.

So there are 3 options here:

1. Try to figure out the breakage and still get it working with OpenGL
2. Rewrite to Metal API (OpenGL is deprecated on macOS also)
3. Require and older version of the SDK

**Comment by gnilk** [comment] 2020-08-04 08:35
Do you happen to know which SDK can be used to build?

**Comment by emoon** [comment] 2020-08-04 08:37
Yeah, 10.13 should work fine.

**Comment by emoon** [comment] 2021-04-14 06:43
Will be resolved by #159

**Closed by emoon** 2021-04-14 06:43 UTC
